name = "TransitionPaths2024"
uuid = "283aaa48-358f-4a96-80df-ababaedee569"
authors = ["Jorge FdCD <jorgefdcd@icloud.com> and contributors"]
version = "1.0.0-DEV"

[deps]
BioSequences = "7e6ae17a-c86d-528c-b3b9-7f778a29fe59"
BioStructures = "de9282ab-8554-53be-b2d6-f6c222edabfc"
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
CairoMakie = "13f3f980-e62b-5c42-98c6-ff1f3baf88f0"
ColorSchemes = "35d6a980-a343-548e-a6ea-1d62b119f2f4"
DCAUtils = "e41cd558-3099-4f6e-a65d-5336857e40aa"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
DelimitedFiles = "8bb1440f-4735-579b-a4ab-409b98df4dab"
FASTX = "c2308a5c-f048-11e8-3e8a-31650f418d12"
HDF5 = "f67ccb44-e63f-5c2f-98bd-6dc0ccc4ba2f"
HMMER = "59c5aa83-900c-4c4d-b6cc-c9bbbf32a260"
LazyArtifacts = "4af54fe1-eca0-43a8-85a7-787d91b784e3"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
LogExpFunctions = "2ab3a3ac-af41-5b50-aa03-7779005ae688"
Logomaker = "3e22dfff-eee4-477b-ac6a-6f7f49e5ccf0"
Makie = "ee78f7c6-11fb-53f2-987a-cfe4a2b5a57a"
NaNStatistics = "b946abbf-3ea7-4610-9019-9858bfdeaf2d"
Pfam = "275cd14a-065f-44bb-ab7a-e1328a0f1819"
ProgressLogging = "33c8b6b6-d38a-422a-b730-caa89a2f386c"
PythonPlot = "274fc56d-3b97-40fa-a1cd-1b4a50311bf9"
RestrictedBoltzmannMachines = "12e6b396-7db5-4506-8cb6-664a4fe1e50e"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
StringDistances = "88034a9c-02f8-509d-84a9-84ec65e18404"
XLSX = "fdbf4ff8-1666-58a4-91e7-1b58723a45e0"

[compat]
BioSequences = "3.1.6"
BioStructures = "4.5.0"
CSV = "0.10.13"
CairoMakie = "0.15"
ColorSchemes = "3.29.0"
DCAUtils = "1.0.1"
DataFrames = "1.6.1"
DelimitedFiles = "1.9.1"
FASTX = "2.1.4"
HDF5 = "0.17.1"
HMMER = "1.5.0"
LazyArtifacts = "1.10"
LinearAlgebra = "1.11.0"
LogExpFunctions = "0.3.27"
Logomaker = "2.0.1"
Makie = "0.24"
NaNStatistics = "0.6.43"
Pfam = "2.0.1"
ProgressLogging = "0.1.5"
PythonPlot = "1.0.6"
RestrictedBoltzmannMachines = "3.4,4,5"
StatsBase = "0.34.3"
StringDistances = "0.11.2"
XLSX = "0.10.1"
julia = "1.10"
